config/routes.rb
Rails.application.routes.draw do
  # ...auth...
  resources :sessions, only: [:create, :destroy]
  resources :shares, only: [:create, :index]

  # omniauth
  get 'auth/google_oauth2', to: 'sessions#create', as: 'signin'
  get 'auth/:provider/callback', to: 'sessions#create'
  get 'auth/failure', to: redirect('/')

  # password
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#login_attempt'

  get 'signup', to: 'users#new'
  post 'signup', to: 'users#create'

  # general
  get 'signout', to: 'sessions#destroy', as: 'signout'

  # ...application...
  resources :recipes
  root "landing_pages#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/authorization.rb
class Authorization < ApplicationRecord
  validates :uid, :provider, presence: true
  validates :uid, uniqueness: { scope: :provider }

  belongs_to :user

  def self.from_omniauth(auth, user=nil)
    user ||= User.from_omniauth(auth)

    where(provider: auth.provider, uid: auth.uid).first_or_initialize.tap do |auth|
      auth.user = user
      auth.save!
    end
  end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :shares
  has_many :users, through: :shares, source: :recipient

  validates :name, :url, presence: true
  validates :url, url: true

  def editable?
    !locked?
  end

  def locked?
    shares.merge(Share.with_other_user).any?
  end
end

app/models/share.rb
class Share < ApplicationRecord
  belongs_to :recipe
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User", optional: true

  validates :recipient_email, presence: true
  validates :recipient_email, uniqueness: { scope: :recipe }
  validates :recipient, uniqueness: { scope: :recipe }, allow_nil: true

  before_create :generate_token

  scope :with_other_user, lambda { where("sender_id != recipient_id OR recipient_id IS NULL") }

  def number_of_users_with_recipe
    @number_of_users_with_recipe ||= User.joins(:received_shares).
      where(shares: { recipe_id: recipe.id }).count
  end

  def generate_token
     self.token = Digest::SHA1.hexdigest(
       [self.recipe_id, self.sender_id, Time.now].join
     )
  end
end

app/models/user.rb
class User < ApplicationRecord
  NO_PASSWORD_DIGEST = "NA"

  has_secure_password

  validates :password, length: { minimum: 6 }, allow_nil: true

  validates :email, uniqueness: true
  validates :email, email_format: true

  has_many :sent_shares, foreign_key: :sender_id, class_name: "Share"
  has_many :sent_recipes, through: :sent_shares, source: :recipe

  has_many :received_shares, foreign_key: :recipient_id, class_name: "Share"
  has_many :received_recipes, through: :received_shares, source: :recipe

  has_many :authorizations

  def self.from_omniauth(auth)
    where(email: auth.info.email).first_or_create(
      first_name: auth.info.first_name,
      last_name: auth.info.last_name,
      password_digest: NO_PASSWORD_DIGEST,
    )
  end

  def full_name
    [first_name, last_name].join(" ")
  end

  def authenticates_with_password?
    password_digest != NO_PASSWORD_DIGEST
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :require_login

  helper_method :current_user, :logged_in?

  def require_login
    redirect_to root_path unless logged_in?
  end

  def logged_in?
    current_user.present?
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
end

app/controllers/landing_pages_controller.rb
class LandingPagesController < ApplicationController
  skip_before_action :require_login, only: [:index]

  def index
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show, :edit, :update]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = current_user.received_recipes
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
    @share = Share.new(recipe: @recipe, sender: current_user)
    @my_shares = Share.with_other_user.where(sender: current_user, recipe: @recipe)
  end

  # GET /recipes/new
  def new
    @recipe = Recipe.new
  end

  # GET /recipes/1/edit
  def edit
  end

  # POST /recipes
  # POST /recipes.json
  def create
    @recipe = Recipe.
      where(url: recipe_params[:url], name: recipe_params[:name]).
      first_or_create

    share = current_user.received_shares.where(recipe: @recipe).first_or_initialize(
      sender: current_user,
      recipient_email: current_user.email
    )

    respond_to do |format|
      if @recipe.save && share.save
        format.html { redirect_to @recipe, notice: 'Recipe was successfully created.' }
        format.json { render :show, status: :created, location: @recipe }
      else
        format.html { render :new }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recipes/1
  # PATCH/PUT /recipes/1.json
  def update
    respond_to do |format|
      if @recipe.update(recipe_params)
        format.html { redirect_to @recipe, notice: 'Recipe was successfully updated.' }
        format.json { render :show, status: :ok, location: @recipe }
      else
        format.html { render :edit }
        format.json { render json: @recipe.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      begin
        @recipe = current_user.received_recipes.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        redirect_to shares_path
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.require(:recipe).permit(:url, :name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login, only: [:create, :new, :login_attempt]

  def new
  end

  def login_attempt
    user = User.where(email: params[:email]).first

    if user&.authenticates_with_password? && user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to shares_path
    else
      redirect_to login_path
    end
  end

  def create
    auth = Authorization.from_omniauth(request.env["omniauth.auth"])
    session[:user_id] = auth.user.id

    if share.present?
      share.update!(recipient: auth.user)
    end

    redirect_to shares_path
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end

  private

  def share
    @share ||= Share.find_by(token: share_token)
  end

  def share_token
    cookies[:share_token]
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController
  def new
    @share = Share.new
  end

  def index
    @received_shares = current_user.received_shares
  end

  def create
    @share = Share.where(share_params).first_or_initialize
    @share.sender = current_user
    @share.recipient = User.where(email: @share.recipient_email).first

    if @share.save
      if @share.recipient.present?
        SharesMailer.notify_existing_user(@share).deliver
      else
        SharesMailer.notify_recipient(@share).deliver
      end

      flash[:notice] = "You've shared a recipe! :party-parrot-shuffle:"
    else

      flash[:error] = @share.errors.full_messages.to_sentence
    end

    redirect_to @share.recipe
  end

  private

  def share_params
    params.require(:share).permit(:recipe_id, :recipient_email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :require_login, only: [:new, :create]

  def new
    update_share_token_cookie
    @user = User.new
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      share.update!(recipient: @user) if share.present?
      redirect_to shares_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end

  def share
    @share ||= Share.find_by(token: share_token)
  end

  def share_token
    update_share_token_cookie
    cookies[:share_token]
  end

  def update_share_token_cookie
    cookies[:share_token] = params[:share_token] if params[:share_token].present?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/landing_pages/index.html.erb
<div class="mt-5 text-center" >
  <h2>Reciparrot</h2>
  <h6 class="text-muted ">Share DELICIOUS recipes with the recipe parrot</h6>

  <% if logged_in? %>
    <%= button_to "Start Sharing", shares_path, method: :get, class: "btn btn-primary mt-2" %>
  <% else %>
    <%= button_to "Start Sharing", signup_path, method: :get, class: "btn btn-primary mt-2" %>
  <% end %>
</div>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <div class="container">
    <span class="text-muted">
      Copyright &copy; <%= Date.today.year %>
      <%= link_to "Reciparrot", "https://twitter.com/intent/follow?screen_name=reciparrot" %>
    </span>
  </div>
</footer>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-toggleable-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <a class="navbar-brand" href="/">
    <%= image_tag("parrot.png", alt: "parrot", width: 30) %>
    Reciparrot
  </a>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <% if logged_in? %>
      <li class="nav-item">
        <%= link_to "Add Recipe", new_recipe_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "My Recipes", shares_path, class: "nav-link" %>
      </li>
    <% end %>
    </ul>

    <ul class="navbar-nav">
    <% if current_user %>
      <li class="nav-item">
        <%= link_to "Logout #{current_user.first_name}", signout_path, id: "sign_out" %>
      </li>
    <% else %>
      <li class="nav-item">
        <%= link_to "Login", login_path, id: "login", class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Signup", signup_path, id: "signup", class: "nav-link" %>
      </li>
    <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Reciparrot</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render partial: "layouts/header" %>

    <div class="container mt-3">
      <%= yield %>
    </div>

    <%= render partial: "layouts/footer" %>
  </body>
</html>

app/views/recipes/_form.html.erb
<%= form_for(recipe) do |f| %>
  <% if recipe.locked? %>
    <fieldset disabled>
  <% end %>

  <% if recipe.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this recipe from being saved:</h2>

      <ul>
      <% recipe.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group row">
    <label for="example-text-input" class="col-2 col-form-label">Name</label>
    <div class="col-10">
      <%= f.text_field :name, class: "form-control" %>
    </div>
  </div>

  <div class="form-group row">
    <label for="example-text-input" class="col-2 col-form-label">URL</label>
    <div class="col-10">
      <%= f.text_field :url, class: "form-control", type: "url" %>
    </div>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

  <% if recipe.locked? %>
    </fieldset>
  <% end %>
<% end %>

app/views/recipes/edit.html.erb
<%= render "form", recipe: @recipe %>
<%= link_to "Back to recipe", recipe_path(@recipe) %>

app/views/recipes/new.html.erb
<%= render "form", recipe: @recipe %>
<%= link_to "My Recipes", shares_path %>

app/views/recipes/show.html.erb
<div class="container">
  <% flash.each do |key, value| %>
    <p><%= "#{key}: #{value}" %></p>
  <% end %>

  <div class="row">
    <div class="col">
      <h2><%= @recipe.name %></h2>
    </div>
    <div class="col">
      <%= render "shares/form", share: @share %>
    </div>
  </div>

  <div class="row">
    <div class="col">
      <p><%= link_to @recipe.url, @recipe.url %></p>
      <% if @recipe.editable? %>
        <%= link_to "Edit", edit_recipe_path(@recipe) %>
      <% end %>

      <% if @my_shares.any? %>
        <h6 class="mt-5">Shared with:</h6>
        <table class="table">
          <tbody>
            <% @my_shares.each do |share| %>
              <tr>
                <td><%= share.recipient_email %></td>
              </tr>
            <% end %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>

app/views/shares/_form.html.erb
<%= form_for(share) do |f| %>
  <% if share.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(recipe.errors.count, "error") %> prohibited this share from being saved:</h2>

      <ul>
        <% share.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :recipe_id, value: @share.recipe_id %>

  <div class="form-group row">
    <div class="col-8">
      <%= f.text_field :recipient_email, class: "form-control", type: "email", placeholder: "hank.scorpio@globex.com" %>
    </div>

    <div class="actions">
      <%= f.submit "Share!", class: "btn btn-primary", type: "submit" %>
    </div>
  </div>
<% end %>

app/views/shares/_sadparrot.html.erb
<%= image_tag("sadparrot.gif", alt: "sad-parrot") %>

<p class="font-weight-bold mt-2">
You don't have any recipes yet.
</p>

<%= link_to "Add Recipe", new_recipe_path, class: "btn btn-primary mt-2" %>

<div class="align-text-bottom mt-5">
  <p class="font-weight-">
  Sad parrot credit
  <a href="https://github.com/jmhobbs/cultofthepartyparrot.com/pull/10">
    Glen Takahashi
  </a>
  </p>
</div>

app/views/shares/_table.html.erb
<table class="table" align="center">
  <thead>
    <tr>
      <th>Recipe</th>
      <th>Shared By</th>
      <th>:Parrots:</th>
    </tr>
  </thead>
  <tbody>
    <% @received_shares.each do |share| %>
      <tr>
        <td><%= link_to "#{share.recipe.name}", share.recipe %></td>
        <td><%= share.sender == current_user ? "Mine!" : share.sender.full_name %></td>
        <td><%= share.number_of_users_with_recipe %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/shares/index.html.erb
<% if @received_shares.any? %>
  <%= render partial: "shares/table" %>
<% else %>
  <%= render partial: "shares/sadparrot" %>
<% end %>

app/views/users/new.html.erb
<div class="row justify-content-center mt-3">
  <div class="col-8">
    <h2 class="mt-2">
      Signing up lets you share recipes
    </h2>

    <%= form_tag signin_path do %>
      <div class="mb-4 mt-3 offset-sm-2 col-sm-10">
        <%= image_submit_tag "google_signin_buttons/web/1x/btn_google_signin_dark_normal_web.png" %>
      </div>
    <% end %>

    <h6 class="mt-2">
      Or if you prefer, sign up by hand by hand:
    </h6>
  </div>
</div>

<div class="row justify-content-center mt-3">
  <div class="col-8">
    <%= form_for(:user) do |f| %>
      <% if @user.errors.any? %>
        <div id="error_explanation">
          <h2>You need to fix some errors:</h2>

          <ul>
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">First Name</label>
        <div class="col-6">
          <%= f.text_field :first_name, class: "form-control", type: "text", placeholder: "Hank" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Last Name</label>
        <div class="col-6">
          <%= f.text_field :last_name, class: "form-control", type: "text", placeholder: "Scorpio" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Email</label>
        <div class="col-6">
          <%= f.text_field :email, class: "form-control", type: "email", placeholder: "hank.scorpio@globex.com" %>
        </div>
      </div>

      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Password</label>
        <div class="col-6">
          <%= f.text_field :password, class: "form-control", type: "password" %>
          <p id="passwordHelpBlock" class="form-text text-muted">
            Must be more than 6 characters.
          </p>
        </div>
      </div>

      <div class="form-group row">
        <label for="example-password-input" class="col-2 col-form-label">Password Confirmation</label>
        <div class="col-6">
          <%= f.text_field :password_confirmation, class: "form-control", type: "password" %>
        </div>
      </div>

      <div class="mb-4 offset-sm-2 col-sm-10">
        <%= f.submit "Start sharing", class: "btn btn-primary", type: "submit" %>
      </div>
    <% end %>
  </div>
</div>